# =============================================
# Mosquitto Broker Configuration
# MQTT Project - Integrasi Sistem
# =============================================

# --- Listener MQTT standar (untuk Python clients) ---
listener 1883
allow_anonymous true

# --- Listener WebSocket (untuk Web Dashboard) ---
listener 9001
protocol websockets
allow_anonymous true

# --- Logging ---
log_type all
log_dest stdout

# --- Persistence (untuk retain messages) ---
persistence true
persistence_location C:\mqtt_data\

# --- Retained messages ---
retain_available true

# --- QoS Settings ---
max_qos 2